<?php
namespace app\components;
use yii\base\Widget;
use Yii;

/**
 * Created by PhpStorm.
 * User: Андрей
 * Date: 09.10.2016
 * Time: 17:27
 */

class MenuWidget extends Widget{

    public $tpl;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if($this->tpl === null){
            $this->tpl = 'menu_header_tpl';//
        }
        $this->tpl .= '.php';
    }

    public function run()
{
   return $this->tpl;
}
}